### PR TITLE
Checking if hoogle executable is available and if the database is generated

### PR DESCRIPTION
**Pull request by kubek2k**
also the startup messages are persisted now.

### CODE REVIEW

**Comment by monkoose** [comment]
Hello @kubek2k 
I don't have anything against checking if `hoogle` is executable (even if i think it is a little bit excess) and echom.
But system() in the plugin's initializing phase is not a good idea. In reality there shouldn't be any problem, but because it is synchronous it can cause problems or at least slow down vim startup.

I will think about if there are better ways to check if the database is generated and if not system() call should be moved to autoload directory.

**Comment by kubek2k** [comment]
@monkoose sure - I will also give it a look. I appreciate your feedback, since my vimscript fu is low ;)

**Comment by kubek2k** [comment]
@monkoose looking through the hoogle codebase it seems like it doesn't differentiate the status code when the database is not in place. Maybe it does make sense to record the output message of failed `hoogle` invocation to the messages, and print a common failure message in the end on every error?

**Comment by monkoose** [comment]
I merged first two commits from your PR. Closed.

**Pull request closed without merging**
